name: Super-Linter
run-name: ${{ github.actor }} is running Super-Linter
on: push
jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}